# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from memory_core.v1 import memory_pb2 as memory__core_dot_v1_dot_memory__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in memory_core/v1/memory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MemoryCoreStub(object):
    """MemoryCore is the harness-neutral public boundary of the authoritative core.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ObserveSourceEvent = channel.unary_unary(
                '/memory.v1.MemoryCore/ObserveSourceEvent',
                request_serializer=memory__core_dot_v1_dot_memory__pb2.ObserveSourceEventRequest.SerializeToString,
                response_deserializer=memory__core_dot_v1_dot_memory__pb2.SourceEventReceipt.FromString,
                _registered_method=True)
        self.SelectMemory = channel.unary_unary(
                '/memory.v1.MemoryCore/SelectMemory',
                request_serializer=memory__core_dot_v1_dot_memory__pb2.SelectMemoryRequest.SerializeToString,
                response_deserializer=memory__core_dot_v1_dot_memory__pb2.MemoryContext.FromString,
                _registered_method=True)
        self.RecordMemoryDelivery = channel.unary_unary(
                '/memory.v1.MemoryCore/RecordMemoryDelivery',
                request_serializer=memory__core_dot_v1_dot_memory__pb2.MemoryDeliveryReceipt.SerializeToString,
                response_deserializer=memory__core_dot_v1_dot_memory__pb2.ReceiptAck.FromString,
                _registered_method=True)
        self.ReportOutcome = channel.unary_unary(
                '/memory.v1.MemoryCore/ReportOutcome',
                request_serializer=memory__core_dot_v1_dot_memory__pb2.ReportOutcomeRequest.SerializeToString,
                response_deserializer=memory__core_dot_v1_dot_memory__pb2.OutcomeReceipt.FromString,
                _registered_method=True)


class MemoryCoreServicer(object):
    """MemoryCore is the harness-neutral public boundary of the authoritative core.
    """

    def ObserveSourceEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SelectMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordMemoryDelivery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportOutcome(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoryCoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ObserveSourceEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.ObserveSourceEvent,
                    request_deserializer=memory__core_dot_v1_dot_memory__pb2.ObserveSourceEventRequest.FromString,
                    response_serializer=memory__core_dot_v1_dot_memory__pb2.SourceEventReceipt.SerializeToString,
            ),
            'SelectMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.SelectMemory,
                    request_deserializer=memory__core_dot_v1_dot_memory__pb2.SelectMemoryRequest.FromString,
                    response_serializer=memory__core_dot_v1_dot_memory__pb2.MemoryContext.SerializeToString,
            ),
            'RecordMemoryDelivery': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordMemoryDelivery,
                    request_deserializer=memory__core_dot_v1_dot_memory__pb2.MemoryDeliveryReceipt.FromString,
                    response_serializer=memory__core_dot_v1_dot_memory__pb2.ReceiptAck.SerializeToString,
            ),
            'ReportOutcome': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportOutcome,
                    request_deserializer=memory__core_dot_v1_dot_memory__pb2.ReportOutcomeRequest.FromString,
                    response_serializer=memory__core_dot_v1_dot_memory__pb2.OutcomeReceipt.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memory.v1.MemoryCore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memory.v1.MemoryCore', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemoryCore(object):
    """MemoryCore is the harness-neutral public boundary of the authoritative core.
    """

    @staticmethod
    def ObserveSourceEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.MemoryCore/ObserveSourceEvent',
            memory__core_dot_v1_dot_memory__pb2.ObserveSourceEventRequest.SerializeToString,
            memory__core_dot_v1_dot_memory__pb2.SourceEventReceipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SelectMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.MemoryCore/SelectMemory',
            memory__core_dot_v1_dot_memory__pb2.SelectMemoryRequest.SerializeToString,
            memory__core_dot_v1_dot_memory__pb2.MemoryContext.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordMemoryDelivery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.MemoryCore/RecordMemoryDelivery',
            memory__core_dot_v1_dot_memory__pb2.MemoryDeliveryReceipt.SerializeToString,
            memory__core_dot_v1_dot_memory__pb2.ReceiptAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportOutcome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.MemoryCore/ReportOutcome',
            memory__core_dot_v1_dot_memory__pb2.ReportOutcomeRequest.SerializeToString,
            memory__core_dot_v1_dot_memory__pb2.OutcomeReceipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
