# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: memory_core_worker/v1/inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'memory_core_worker/v1/inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%memory_core_worker/v1/inference.proto\x12\x13memory.inference.v1\"\xb9\x01\n!ProcessConsolidationWindowRequest\x12\x0f\n\x07job_ref\x18\x01 \x01(\t\x12\x13\n\x0bwindow_text\x18\x02 \x01(\t\x12\x1b\n\x13\x61llowed_target_refs\x18\x03 \x03(\t\x12\x1a\n\x12\x61llowed_basis_refs\x18\x04 \x03(\t\x12\x35\n\x08\x65vidence\x18\x05 \x01(\x0b\x32#.memory.inference.v1.WindowEvidence\"\xc2\x01\n\x0eWindowEvidence\x12\x36\n\x08\x65pisodes\x18\x01 \x03(\x0b\x32$.memory.inference.v1.EvidenceEpisode\x12\x36\n\x08outcomes\x18\x02 \x03(\x0b\x32$.memory.inference.v1.EvidenceOutcome\x12@\n\rrecollections\x18\x03 \x03(\x0b\x32).memory.inference.v1.EvidenceRecollection\"\x99\x01\n\x0f\x45videnceEpisode\x12\x13\n\x0b\x65pisode_ref\x18\x01 \x01(\t\x12\x13\n\x0bsession_ref\x18\x02 \x01(\t\x12\x0e\n\x06origin\x18\x03 \x01(\t\x12\x34\n\x07sources\x18\x04 \x03(\x0b\x32#.memory.inference.v1.EvidenceSource\x12\x16\n\x0e\x66ormation_role\x18\x05 \x01(\t\"g\n\x0e\x45videnceSource\x12\x12\n\nsource_ref\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\x12\x12\n\nactor_kind\x18\x03 \x01(\t\x12\x11\n\tactor_ref\x18\x04 \x01(\t\x12\x0c\n\x04text\x18\x05 \x01(\t\"p\n\x0f\x45videnceOutcome\x12\x13\n\x0boutcome_ref\x18\x01 \x01(\t\x12\x13\n\x0b\x65pisode_ref\x18\x02 \x01(\t\x12\x12\n\nactor_kind\x18\x03 \x01(\t\x12\x11\n\tactor_ref\x18\x04 \x01(\t\x12\x0c\n\x04text\x18\x05 \x01(\t\"N\n\x14\x45videnceRecollection\x12\x13\n\x0bversion_ref\x18\x01 \x01(\t\x12\x13\n\x0b\x61pplication\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\")\n\x12TaggedTextResponse\x12\x13\n\x0btagged_text\x18\x01 \x01(\t2\x90\x01\n\x0fInferenceWorker\x12}\n\x1aProcessConsolidationWindow\x12\x36.memory.inference.v1.ProcessConsolidationWindowRequest\x1a\'.memory.inference.v1.TaggedTextResponseBAZ?github.com/aig-dev/ChoraMem/gen/memory/inference/v1;inferencev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'memory_core_worker.v1.inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z?github.com/aig-dev/ChoraMem/gen/memory/inference/v1;inferencev1'
  _globals['_PROCESSCONSOLIDATIONWINDOWREQUEST']._serialized_start=63
  _globals['_PROCESSCONSOLIDATIONWINDOWREQUEST']._serialized_end=248
  _globals['_WINDOWEVIDENCE']._serialized_start=251
  _globals['_WINDOWEVIDENCE']._serialized_end=445
  _globals['_EVIDENCEEPISODE']._serialized_start=448
  _globals['_EVIDENCEEPISODE']._serialized_end=601
  _globals['_EVIDENCESOURCE']._serialized_start=603
  _globals['_EVIDENCESOURCE']._serialized_end=706
  _globals['_EVIDENCEOUTCOME']._serialized_start=708
  _globals['_EVIDENCEOUTCOME']._serialized_end=820
  _globals['_EVIDENCERECOLLECTION']._serialized_start=822
  _globals['_EVIDENCERECOLLECTION']._serialized_end=900
  _globals['_TAGGEDTEXTRESPONSE']._serialized_start=902
  _globals['_TAGGEDTEXTRESPONSE']._serialized_end=943
  _globals['_INFERENCEWORKER']._serialized_start=946
  _globals['_INFERENCEWORKER']._serialized_end=1090
# @@protoc_insertion_point(module_scope)
