# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from memory_core_worker.v1 import inference_pb2 as memory__core__worker_dot_v1_dot_inference__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in memory_core_worker/v1/inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InferenceWorkerStub(object):
    """InferenceWorker is an internal, stateless text-processing boundary.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessConsolidationWindow = channel.unary_unary(
                '/memory.inference.v1.InferenceWorker/ProcessConsolidationWindow',
                request_serializer=memory__core__worker_dot_v1_dot_inference__pb2.ProcessConsolidationWindowRequest.SerializeToString,
                response_deserializer=memory__core__worker_dot_v1_dot_inference__pb2.TaggedTextResponse.FromString,
                _registered_method=True)


class InferenceWorkerServicer(object):
    """InferenceWorker is an internal, stateless text-processing boundary.
    """

    def ProcessConsolidationWindow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceWorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessConsolidationWindow': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessConsolidationWindow,
                    request_deserializer=memory__core__worker_dot_v1_dot_inference__pb2.ProcessConsolidationWindowRequest.FromString,
                    response_serializer=memory__core__worker_dot_v1_dot_inference__pb2.TaggedTextResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memory.inference.v1.InferenceWorker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memory.inference.v1.InferenceWorker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InferenceWorker(object):
    """InferenceWorker is an internal, stateless text-processing boundary.
    """

    @staticmethod
    def ProcessConsolidationWindow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.inference.v1.InferenceWorker/ProcessConsolidationWindow',
            memory__core__worker_dot_v1_dot_inference__pb2.ProcessConsolidationWindowRequest.SerializeToString,
            memory__core__worker_dot_v1_dot_inference__pb2.TaggedTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
